Add enabled flag to the Confidential widget
wiredashio/wiredash-sdk pull request #64
Opened 2020-07-04 23:22 UTC by creativecreatorormaybenot

If you have something like an `itemBuilder` or any other case, where you return a single widget tree for items that might handle confidentiality differently, this flag is useful.

---

I also think that `PaintItBlack` should not be in the public API (I was a bit confused by it when looking into the API reference and it is not good practice to expose it for the sake of breaking changes I would say). I think this can go without a breaking change because it would be weird for anyone to have used this,

2020-07-04 23:32 UTC, creativecreatorormaybenot commented
@flschweiger Is there anything I can do to make the build run properly/have the required check pass? 🙂

2020-09-16 14:52 UTC, roughike requested changes

2020-09-16 14:52 UTC, roughike commented on lib/src/common/widgets/confidential.dart
> +        Offset.zero & size,
love this :-)

2020-09-16 14:52 UTC, roughike commented on lib/src/common/widgets/confidential.dart
> +    this.enabled = true,
How would you feel about getting rid of this extra boolean flag and adding a new `ConfidentialMode.none` enum value instead? :-)

(and thanks for fixing the formatting!)

2020-09-16 15:04 UTC, creativecreatorormaybenot commented on lib/src/common/widgets/confidential.dart
> +    this.enabled = true,
@roughike Thanks for your review 👌🏽🥳

I thought about this and my reasoning was something like this:

* Disabling is not really a confidential mode - it is just not confidential.
* I like that it is a boolean flag because it removes the need for a weird ternary operator.

```dart
return Confidential(
  mode: index == 0 ? ConfidentialMode.none : ConfidentialMode.black,
  ..
);

// vs

return Confidential(
  mode: ConfidentialMode.black,
  enabled: index != 0,
  ..
);
````

In the first case, it is not clear at first glance whether there is a single confidential mode or possibly different kinds of them used (need to go through the expression mentally).  
In the second case, it is clear that the mode used is `black` and that it is sometimes enabled and sometimes not.

---

In the end, it does not really matter.  

I tried to follow [`Offstage`](https://api.flutter.dev/flutter/widgets/Offstage-class.html) et al.

What do you prefer?

2020-09-16 15:51 UTC, roughike commented on lib/src/common/widgets/confidential.dart
> +    this.enabled = true,
> I like that it is a boolean flag because it removes the need for a weird ternary operator.

I actually like the code sample with a boolean flag - it does look cleaner!

> I tried to follow Offstage et al.

`Offstage` has a single boolean value called `enabled` in it with no additional `OffstageMode` or an equivalent argument, so I don't see how it applies here.

I can't from the top of my mind call a Flutter widget that takes in an enum value and a boolean, that depending on if true or false, disables said enum argument. It kinda brings me memories of my childhood home where you had to turn two light switches on before the light would come. If one of them was in the wrong position, the other one had no effect.

But I think keeping the boolean is totally fine, just wanted to pick your brain a bit :-)

2020-09-16 15:54 UTC, roughike approved these changes
thanks for the PR and sorry for the long wait! I think I'll pull this into the next release.

![giphy (1)](https://user-images.githubusercontent.com/13744304/93361736-dd77af00-f84d-11ea-9f33-310a957822c6.gif)

2020-09-16 17:04 UTC, merged